seed: 42

# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/develop/modules/skrl.utils.model_instantiators.html
models:
  separate: False
  policy:  # see skrl.utils.model_instantiators.gaussian_model for parameter details
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    input_shape: "Shape.STATES"
    hiddens: [32, 32]
    hidden_activation: ["leaky_relu", "leaky_relu", "leaky_relu"]
    output_shape: "Shape.ACTIONS"
    output_activation: "tanh"
    output_scale: 1.0
  value:  # see skrl.utils.model_instantiators.deterministic_model for parameter details
    clip_actions: False
    input_shape: "Shape.STATES"
    hiddens: [32, 32]
    hidden_activation: ["leaky_relu", "leaky_relu", "leaky_relu"]
    output_shape: "Shape.ONE"
    output_activation: ""
    output_scale: 1.0


#   learning_rate_scheduler: "KLAdaptiveRL"
agent:
  actor_learning_rate: 1.e-4
  critic_learning_rate: 1.e-4
  batch_size: 4096
  #learning_rate_scheduler: "None"
  #learning_rate_scheduler_kwargs: null
  #state_preprocessor: "None"
  #state_preprocessor_kwargs: null
  #value_preprocessor: "None"
  #value_preprocessor_kwargs: null
  entropy_learning_rate: 5.e-3
  random_timesteps: 0
  learning_starts: 0

  #rewards_shaper_scale: null
  # logging and checkpoint
  experiment:
    directory: "rover"
    experiment_name: ""
    write_interval: 40
    checkpoint_interval: 400
    wandb: True             # whether to use Weights & Biases

trainer:
  timesteps: 200000
  batch_size: 4096
