config:
  batch_size: 64
  camera_tilt: 0.15
  cost_map_name: cost_map_sem_sharpend
  data_cfg:
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: true
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      4: 0.05
      7.5: 0.6
      10: 0.3
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: 3000
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: true
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      4: 0.05
      7.5: 0.6
      10: 0.3
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: 3000
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  - !!python/object:viplanner.config.learning_cfg.DataCfg
    carla: false
    depth_gaussian: null
    depth_random_polygon_size: 10
    depth_random_polygons_nb: null
    depth_salt_pepper: null
    depth_scale: 1000.0
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    edge_threshold: 100
    extend_kernel_size:
    - 5
    - 5
    fov_scale: 1.0
    max_depth: 15.0
    max_goal_distance: 15.0
    max_train_pairs: null
    min_goal_distance: 0.5
    noise_edges: false
    obs_cost_height: 1.5
    pairs_per_image: 4
    ratio: 0.9
    ratio_back_samples: 0.01
    ratio_fov_samples: 0.96
    ratio_front_samples: 0.03
    real_world_data: false
    sem_rgb_black_img: null
    sem_rgb_pepper: null
    sem_rgb_random_polygon_size: 20
    sem_rgb_random_polygons_nb: null
  decoder_small: false
  env_list:
  - 2azQ1b91cZZ_cam_mount
  - JeFG25nYj2p_cam_mount
  - warehouse_multiple_shelves_without_ppl
  - town01_cam_mount_train
  - Vvot9Ly1tCj_cam_mount
  - E9uDoFAP3SH_cam_mount
  - warehouse_multiple_shelves_without_ppl
  - ur6pFq6Qu1A_cam_mount
  - B6ByNegPMKs_cam_mount
  - warehouse_multiple_shelves_without_ppl
  - 8WUmhLawc2A_cam_mount
  - town01_cam_mount_train
  - QUCTc6BB5sX_cam_mount
  - warehouse_multiple_shelves_without_ppl
  - YFuZgdQ5vWj_cam_mount
  - 2n8kARJN3HM_cam_mount
  epochs: 100
  factor: 0.5
  fear_ahead_dist: 2.5
  file_name: new_cam_mount_combi_lossWidthMod_wgoal4.0_warehouse
  file_path: /home/pascal/SemNav/imperative_learning
  gpu_id: 0
  hierarchical: false
  hierarchical_back_step_ratio: 0.01
  hierarchical_front_step_ratio: 0.02
  hierarchical_step: 50
  img_input_size:
  - 360
  - 640
  in_channel: 16
  knodes: 5
  load_in_ram: false
  lr: 0.002
  min_lr: 1.0e-05
  momentum: 0.1
  multi_epoch_dataloader: false
  n_visualize: 16
  num_workers: 4
  optimizer: sgd
  patience: 3
  pre_train_cfg: m2f_model/coco/panoptic/maskformer2_R50_bs16_50ep.yaml
  pre_train_freeze: true
  pre_train_sem: true
  pre_train_weights: m2f_model/coco/panoptic/model_final_94dc52.pkl
  resume: false
  rgb: false
  seed: 0
  sem: true
  test_env_id: 15
  w_decay: 0.0001
  w_goal: 4.0
  w_height: 1.0
  w_motion: 1.5
  w_obs: 0.25
  wb_entity: viplanner
  wb_project: SemNav-NewColorspace
loss:
  test_loss: 8.24063568496704
  val_loss: 8.098475995695786
